### ISSUE TITLE
Morning session - P2P CR - 09/09

### ISSUE THREAD

**Issue by dicodiaz** [DyaryRaoof/our-courses#2]
Hello @DyaryRaoof, this issue is for all our recommendations for your project.

**Comment by dicodiaz** [comment]
Hello again, @DyaryRaoof. Amazing project, you're doing a great job! 👍 

I do have a few recommendations for it:

### README:
- I recommend applying a link to the "Cindy Shin in Behance" text so that it redirects to her [profile](https://www.behance.net/adagio07).

### CSS:
- I recommend adding right and left padding to the <section id="main-program"> so the programs blocks look centered.
- I recommend adding top padding to the <section id=" partners"> so it looks separated from the previous section.
- I recommend removing the href="index.html" from the anchor in the Home Page and use href="#" since it's not necessary to load it again.
- I recommend removing the background from the logo section in the mobile version since the template indicates no background.
- I recommend replacing the margin of the partners' section of the about page - mobile version for padding since the margin space shows in a different background color.
- I recommend hiding the partners' section of the about page and make the background of the footer dark in the desktop version since the template indicates so.

### HTML:
- I recommend taking the heading section out of the header tag and placing it directly as a child of the body.
- I also recommend, after that, placing the main tag that surrounds every section tag (leaving out the header and the footer), so that the heading section (and every other section) would be a direct child of the main tag.
- For more information about HTML5 semantic tags, read [HTML layout elements in more detail](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#html_layout_elements_in_more_detail)

### JS:
- I have no recommendation, it's perfect!

That's all, everything else is outstanding. Keep up the good work! 😃

**Comment by KatIsCoding** [comment]
## Be more cautious!!

Hi Dyary, your project looks really great and functional, also other than the suggestions @dicodiaz gave I don't really have others that can help you. However, I strongly recommend always test your project multiple times before submitting it, this way you will be 100% sure everything is right. Hopefully, everything goes right for you!!

**Comment by DyaryRaoof** [comment]
Changes made as recommened.
